# Generated by Django 4.1.5 on 2023-01-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
