# Generated by Django 4.1.5 on 2023-02-21 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_identity_verifies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskills',
            name='user',
        ),
        migrations.AddField(
            model_name='userskills',
            name='user',
            field=models.ManyToManyField(related_name='skill', to=settings.AUTH_USER_MODEL),
        ),
    ]
