# Generated by Django 4.1.5 on 2023-01-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_usereducation_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Service Provider', 'Service Provider'), ('Service Seeker', 'Service Seeker'), ('Admin', 'Admin')], default='servicee', max_length=20),
        ),
    ]
