# Generated by Django 4.1.5 on 2023-01-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='points',
            field=models.IntegerField(default='100'),
        ),
    ]
