# Generated by Django 4.1.5 on 2023-01-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_points_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='remarks',
            field=models.CharField(blank=True, default='New user points', max_length=200),
        ),
    ]
