# Generated by Django 4.1.5 on 2023-04-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_inquries_email_alter_inquries_name'),
        ('account', '0008_user_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskills',
            name='name',
        ),
        migrations.AddField(
            model_name='userskills',
            name='name',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_skill', to='services.jobskills'),
        ),
    ]
