# Generated by Django 4.1.5 on 2023-04-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_inquries_email_alter_inquries_name'),
        ('account', '0009_remove_userskills_name_userskills_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskills',
            name='name',
            field=models.ManyToManyField(blank=True, related_name='user_skill', to='services.jobskills'),
        ),
    ]
