# Generated by Django 4.1.5 on 2023-01-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_userbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Service Provider', 'Service Provider'), ('Service Seeker', 'Service Seeker'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
