# Generated by Django 4.1.5 on 2023-04-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_userskills_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereducation',
            name='college_university_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
