# Generated by Django 4.1.5 on 2023-04-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_inquries_email_alter_inquries_name'),
        ('account', '0011_usereducation_college_university_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usereducation',
            name='add_degree',
        ),
        migrations.AddField(
            model_name='usereducation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usereducation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='name',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_skill', to='services.jobskills'),
        ),
    ]
