# Generated by Django 4.1.5 on 2023-05-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_usereducation_add_degree_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usereducation',
            old_name='description',
            new_name='edu_description',
        ),
    ]
