# Generated by Django 4.1.5 on 2023-05-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_rename_description_usereducation_edu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereducation',
            name='level',
            field=models.CharField(blank=True, choices=[('illiterate', 'Illiterate'), ('primary', 'Primary Level'), ('seconday', 'Secondary Level'), ('higher_secondary', 'Higher Secondary Level'), ('vocational', 'Vocational'), ('bachelor', 'Bachelor Degree'), ('master', 'Master Degree'), ('doctorate', 'Doctorate')], default='primary', max_length=50),
        ),
    ]
