# Generated by Django 4.1.5 on 2023-05-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_usereducation_degree_alter_usereducation_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereducation',
            name='college_university_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='edu_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
