# Generated by Django 4.1.5 on 2023-02-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_loadbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadbalance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=100),
        ),
    ]
