# Generated by Django 4.1.5 on 2023-01-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='vacancy',
            field=models.IntegerField(default='1', help_text='Enter number of vacancies'),
        ),
    ]
