# Generated by Django 4.1.5 on 2023-01-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.RemoveField(
            model_name='services',
            name='time',
        ),
        migrations.AddField(
            model_name='services',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
