# Generated by Django 4.1.5 on 2023-01-28 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_jobapplications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplications',
            name='service',
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.services'),
        ),
    ]
