# Generated by Django 4.1.5 on 2023-01-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_services_options_remove_services_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='services',
            name='duration',
            field=models.DurationField(blank=True, default='1 day', null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='services.category'),
        ),
    ]
