# Generated by Django 4.1.5 on 2023-01-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_category_alter_services_duration_services_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='services.skills'),
        ),
        migrations.AddField(
            model_name='services',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='services.skills'),
        ),
    ]
