# Generated by Django 4.1.5 on 2023-02-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_jobapplications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplications',
            name='applied_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
