# Generated by Django 4.1.5 on 2023-04-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_inquries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquries',
            name='email',
            field=models.EmailField(help_text='Enter your email', max_length=254),
        ),
        migrations.AlterField(
            model_name='inquries',
            name='name',
            field=models.CharField(help_text='Enter your name', max_length=100),
        ),
    ]
