# Generated by Django 4.1.5 on 2023-04-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_room',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
