# Generated by Django 4.1.5 on 2023-04-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('seen', 'Seen'), ('unseen', 'Unseen')], default='unseen', max_length=100),
        ),
    ]
