DEGREE_LIST=(
    ('B.Tech','Bachelor of Technology'),
    ('M.Tech','Master of Technology'),
    ('MBA','Master of Business Administration'),
    ('MCA','Master of Computer Application'),
    ('BBA','Bachelor of Business Administration'),
    ('BCA','Bachelor of Computer Application'),
    ('B.Sc','Bachelor of Science'),
    ('M.Sc','Master of Science'),
    ('B.Com','Bachelor of Commerce'),
    ('M.Com','Master of Commerce'),
    ('B.A','Bachelor of Arts'),
    ('M.A','Master of Arts'),
    ('B.Ed','Bachelor of Education'),
    ('M.Ed','Master of Education'),
    ('B.Pharma','B.Pharma'),
    ('M.Pharma','M.Pharma'),
    ('B.Li.Sc','B.Li.Sc'),
    ('M.Li.Sc','M.Li.Sc'),
    ('B.Lib','B.Lib'),
    ('M.Lib','M.Lib'),
    ('B.Arch','B.Arch'),
    ('M.Arch','M.Arch'),
    ('B.Des','B.Des'),
    ('M.Des','M.Des'),
    ('BFA','BFA'),
    ('MFA','MFA'),
    ('BHM','BHM'),
    ('MHM','MHM'),
    ('BBA','BBA'),
    ('MBA','MBA'),
    ('BMS','BMS'),
    ('MMS','MMS'),
    ('CS','CS'),
    ('CA','CA'),
    ('ICWA','ICWA'),
    ('LLB','LLB'),
    ('LLM','LLM'),
    ('BDS','BDS'),
    ('MDS','MDS'),
    ('BHMS','BHMS'),
    ('MBBS','MBBS'),
    ('MD','MD'),
    ('MS','MS'),
    ('BAMS','BAMS'),
    ('BPT','BPT'),
    ('MPT','MPT'),
    ('B.Sc.Nursing','B.Sc.Nursing'),
    ('M.Sc.Nursing','M.Sc.Nursing'),
    ('BVSC','BVSC'),
    ('MVSC','MVSC'),
    ('BPEd','BPEd'),
    ('MPEd','MPEd'),
    ('B.P.Ed','B.P.Ed'),
    ('M.P.Ed','M.P.Ed'),
    ('B.P.Ed','B.P.Ed'),
    ('M.P.Ed','M.P.Ed'),

)