# Generated by Django 4.1.5 on 2023-05-05 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_inquries_email_alter_inquries_name'),
        ('reviews', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobreviews',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_service', to='services.services'),
        ),
    ]
